const eventsMap = new Map()

eventsMap.set("action", "tap press")
eventsMap.set("onDoubleTap", "doubletap")
eventsMap.set("onPan", "pan")
eventsMap.set("onPanCancel", "pancancel")
eventsMap.set("onPanEnd", "panend")
eventsMap.set("onPanStart", "panstart")
eventsMap.set("onPinch", "pinch")
eventsMap.set("onPinchCancel", "pinchcancel")
eventsMap.set("onPinchEnd", "pinchend")
eventsMap.set("onPinchIn", "pinchin")
eventsMap.set("onPinchOut", "pinchout")
eventsMap.set("onPinchStart", "pinchstart")
eventsMap.set("onPress", "press")
eventsMap.set("onPressUp", "pressup")
eventsMap.set("onRotate", "rotate")
eventsMap.set("onRotateCancel", "rotatecancel")
eventsMap.set("onRotateEnd", "rotateend")
eventsMap.set("onRotateMove", "rotatemove")
eventsMap.set("onRotateStart", "rotatestart")
eventsMap.set("onSwipe", "swipe")
eventsMap.set("onSwipeRight", "swiperight")
eventsMap.set("onSwipeLeft", "swipeleft")
eventsMap.set("onSwipeUp", "swipeup")
eventsMap.set("onSwipeDown", "swipedown")
eventsMap.set("onTap", "tap")

export default eventsMap
